# Site settings
title: Erin and Dan
email: 
description: Find info about Erin and Dan's wedding here!
baseurl: ""
url: "http://erandan.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  
future: true
markdown: kramdown
highlighter: rouge

# Custom variables
ceremony_time: "4:30pm"
ceremony_date: "Saturday, September 17th"
ceremony_address: "Palmer Street &amp; Humboldt Boulevard"

reception_time: "6:30pm"
reception_date: "Saturday, September 17th"
reception_address: "2810 W Addison Street"

flickr_api_key: "a3220b9a2d3de34088db8284cf1b65a9"
flickr_user_ID: "87249310@N00"

# Build settings